# Generated by Django 5.2.8 on 2025-12-13 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={},
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='fecha_envio',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(default='Sin asunto', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='cuerpo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
