# Generated by Django 5.2.8 on 2025-12-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0002_alter_mensaje_options_remove_mensaje_contenido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='cuerpo',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='creado',
            new_name='fecha_envio',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='leido',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(default='Sin Asunto', max_length=255),
        ),
    ]
